Comment Component
GSG-G9/Rawdaty pull request #64
Opened 2021-02-03 17:48 UTC by Osama-you

2021-02-04 16:37 UTC, Mu7ammadAbed requested changes

2021-02-04 16:37 UTC, Mu7ammadAbed commented on client/src/Components/Common/Comment/index.js
> +              حدف
```suggestion
              حذف
```

2021-02-05 21:56 UTC, alaa-sahloub approved these changes

2021-02-05 22:28 UTC, Mu7ammadAbed commented on client/src/Components/Common/Comment/index.js
> +          <div id="comment-date">{date}</div>
change the div to an appropriate heading `h3` for example and style it to be displayed `inline`

2021-02-05 22:28 UTC, Mu7ammadAbed commented on client/src/Components/Common/Comment/index.js
> +  <div className="Comment" style={{ maxWidth }} {...otherProps}>
What's the point of `maxWidth`?
There's only 2 cases `isAdmin` and the normal comment

2021-02-06 01:11 UTC, Mu7ammadAbed approved these changes

2021-02-06 06:14 UTC, Israa91 approved these changes

2021-02-06 09:51 UTC, Alaalser approved these changes

2021-02-06 14:10 UTC, alaa-sahloub approved these changes

2021-02-06 14:11 UTC, merged