Search Component
GSG-G9/Rawdaty pull request #69
Opened 2021-02-06 15:15 UTC by Osama-you

2021-02-07 15:11 UTC, Israa91 commented on client/src/Components/Common/Search/index.js
> +  dorpListOptions: PropTypes.arrayOf(PropTypes.object).isRequired,
To validate array of objects , I think it is better to validate the items inside the object like this 
```
 dorpListOptions: PropTypes.arrayOf(
    PropTypes.shape({
      id : PropTypes.number,
      value: PropTypes.string,
      disabled: PropTypes.bool,
    })
  ).isRequired,,
```

2021-02-08 14:09 UTC, Mu7ammadAbed requested changes

2021-02-08 14:09 UTC, Mu7ammadAbed commented on client/src/Components/Search/style.css
> +}
There's a lot of duplicated code here

```suggestion
.search-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-content: space-between;
  margin: 0 20px;
}

@media screen and (max-width: 1062px) {
  .search-container {
    height: 154px;
    align-content: space-around;
  }
}
.input-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.search-options {
  box-shadow: var(--input-shadow);
  border: var(--input-border);
  display: flex;
  padding: 8px 15px;
  border-radius: var(--border-radius);
  max-height: 52px;
}

.search-options,
.search-input {
  margin-left: 20px;
}

@media only screen and (max-width: 768px) {
  .search-options {
    margin: 0;
  }
}

.search-options .drop-list {
  border-left: solid 1px #c4c4c4;
  margin-left: 20px;
  min-width: 126px;
}

.search-options .drop-list img {
  width: 15px;
}

.search-options .price-icon {
  width: 26px;
  margin-left: 10px;
}

.search-options .price-text {
  line-height: 32px;
  margin: 0 0 0 10px;
}

.search-options .slider-label {
  line-height: 38px;
}

.search-input svg {
  font-size: 21px;
}

.search-input input {
  font-size: 17px;
}

.search-container .ant-btn {
  width: 95px;
  border-radius: var(--border-radius);
}

.search-container .ant-btn span {
  font-weight: bold;
  font-size: 25px;
}

```

2021-02-08 14:17 UTC, Mu7ammadAbed requested changes

2021-02-08 14:17 UTC, Mu7ammadAbed commented on client/src/Components/Search/index.js
> +          placeholder="أدخل إسم الروضة"
```suggestion
          placeholder="أدخل اسم الروضة"
```

2021-02-08 15:03 UTC, Alaalser approved these changes

2021-02-08 23:29 UTC, Mu7ammadAbed approved these changes

2021-02-08 23:30 UTC, merged