GET | /kindergarten
GSG-G9/Rawdaty pull request #83
Opened 2021-02-09 14:19 UTC by alaa-sahloub

Relates #12

2021-02-10 22:12 UTC, Mu7ammadAbed commented on server/controllers/index.js
> +// const {verifyUser, verifyAdmin} = require('./auth');
```suggestion
const {clientError, serverError} = require('./errorHandle');
```

2021-02-10 22:12 UTC, Mu7ammadAbed commented on server/controllers/kindergartens/getKindergarten.js
> +// const { default: axios } = require('axios');
There's no need to use Axios here

2021-02-10 22:12 UTC, Mu7ammadAbed commented on test/getKindergarten.test.js
> +const request = require('supertest');
Move the content of this file to `index.test.js`

2021-02-10 22:12 UTC, Mu7ammadAbed commented on package.json
> +    "axios": "^0.21.1",
uninstall this

2021-02-10 22:17 UTC, Mu7ammadAbed commented on test/getKindergarten.test.js
> +});
Change this test to `async/await`

```suggestion
describe('Get all kindergartens', () => {
  test('Route /kindergarten status 200, json header', async () => {
    expect.assertions(1);
    const res = await request(app)
      .get('/api/v1/kindergarten')
      .expect(200)
      .expect('Content-Type', /json/);
    const { data } = res.body;
    expect(data).toHaveLength(11);
  });
});
```

2021-02-11 11:41 UTC, Mu7ammadAbed requested changes

2021-02-11 11:41 UTC, Mu7ammadAbed commented on server/database/queries/kindergarten/getKindergartenQuery.js
> +      'SELECT *, (SELECT AVG(comments.rating) AS rating_average FROM comments WHERE comments.kindergarten_id = kindergartens.id), (SELECT COUNT(comments) AS rating_count FROM comments WHERE comments.
```suggestion
      'SELECT *, (SELECT AVG(comments.rating) AS rating_average FROM comments WHERE comments.kindergarten_id = kindergartens.id), (SELECT COUNT(comments) AS rating_count FROM comments WHERE comments.kindergarten_id = kindergartens.id) FROM kindergartens WHERE kindergartens.request_status = 'approved' AND kindergartens.is_enable = 'true'',
```

2021-02-11 13:12 UTC, Mu7ammadAbed approved these changes

2021-02-11 13:12 UTC, Alaalser approved these changes

2021-02-11 13:13 UTC, Osama-you approved these changes

2021-02-11 13:18 UTC, merged