13 get kindergarten comments
GSG-G9/Rawdaty pull request #85
Opened 2021-02-10 14:27 UTC by Israa91

2021-02-10 22:24 UTC, Mu7ammadAbed requested changes

2021-02-10 22:24 UTC, Mu7ammadAbed commented on .gitignore
> +coverage
new line

2021-02-10 22:24 UTC, Mu7ammadAbed commented on server/router/index.js
> +const comment = require('./comment');
```suggestion
const comments = require('./comments');
```

2021-02-10 22:24 UTC, Mu7ammadAbed commented on test/comment.test.js
> +      .get('/api/v1//kindergarten/2/comments')
```suggestion
      .get('/api/v1/kindergarten/2/comments')
```

2021-02-10 22:24 UTC, Mu7ammadAbed commented on test/comment.test.js
> +    expect(res.body.data.length).toBe(2);
```suggestion
    const { data } = res.body;
    expect(data.length).toBe(2);
```

2021-02-11 14:44 UTC, Mu7ammadAbed approved these changes

2021-02-11 14:45 UTC, Osama-you approved these changes

2021-02-11 14:52 UTC, Alaalser approved these changes

2021-02-11 14:54 UTC, alaa-sahloub approved these changes

2021-02-11 14:54 UTC, merged