Create postLocations funtion
GSG-G9/Rawdaty pull request #91
Opened 2021-02-11 14:45 UTC by Alaalser

Relates #79

2021-02-14 11:49 UTC, Mu7ammadAbed requested changes

2021-02-14 11:49 UTC, Mu7ammadAbed commented on test/index.test.js
> +describe('Locations', () => {
split the tests for different routes into different describes

2021-02-14 11:50 UTC, Mu7ammadAbed requested changes

2021-02-14 11:50 UTC, Mu7ammadAbed commented on server/controllers/locations/postLocations/index.js
> +      { subLocation, mainLocation },
```suggestion
    const { subLocation, mainLocation } = await locationSchema.validate(
      req.body,
```

2021-02-14 11:57 UTC, Mu7ammadAbed requested changes

2021-02-14 11:57 UTC, Mu7ammadAbed commented on test/index.test.js
> +    expect(res.body.data).toHaveLength(24);
Return this to `23` again and edit `beforeAll` to `beforeEach` and fix the other test which will fail
```suggestion
    expect(res.body.data).toHaveLength(23);
```

2021-02-14 12:07 UTC, Mu7ammadAbed requested changes
You still didn't edit the `beforeEach` note and fix the tests

2021-02-15 08:19 UTC, Mu7ammadAbed approved these changes

2021-02-15 08:26 UTC, Osama-you approved these changes

2021-02-15 08:31 UTC, alaa-sahloub approved these changes

2021-02-15 08:39 UTC, Israa91 approved these changes

2021-02-15 08:55 UTC, merged